version: '3.1'

services:
  postgresdb:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - 5432:5432
  backend:
    image: dep-inject:v1.0
    container_name: dep-inject-api
    build: ./
    restart: always
    env_file: .env
    environment:
      PGHOST: postgresdb
    depends_on:
      - postgresdb
    ports:
      - published: ${APP_PORT:-8080}
        target: 8080
